### ISSUE TITLE
array_to_xml function redeclare

### ISSUE THREAD

**Issue by mmlado** [jestillore/php-openfire-userservice#2]
When calling two functions fro the same object, php throws exception about redeclaring the array_to_xml function.

Steps to reproduce:
1. Create object for PhpOpenfireUserservice:
$us = new PHPOpenfireUserservice;
$us->setEndpoint('http://example.com:9090/plugins/userService');
$us->setAuthType(PHPOpenfireUserservice::AUTH_SHARED_KEY)
   ->setSharedKey('thisisthesharedkey');
2. Call function to create 2 users:
$user1 = array(
    'username' => 'user1',
    'password' => 'password1'
);

$user2 = array(
    'username' => 'user2',
    'password' => 'password2',
    'name' => 'User Two',
    'email' => 'user@two.com'
);

$res1 = $us->createUser($user1);
$res2 = $us->createUser($user2);

PHP throws the following error on the second createUser call:
Cannot redeclare Jestillore\PhpOpenfireUserservice\array_to_xml() (previously declared in /srv/srv/wrapper/vendor/jestillore/php-openfire-userservice/src/Jestillore/PhpOpenfireUserservice/PHPOpenfireUserservice.php:192)

**Comment by mmlado** [comment]
I've moved the function to the root of the class and called it using self::
If you can replicate the bug and like the solution you can merge the pull request I sent.

**Comment by jestillore** [comment]
Merged. Thanks.
